name: WINS International Limited
favicon: null
layout_spectrum: 0.7630863392259926
typography_spectrum: 0.8100144995842129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5769804613664746
  lightness: 0.113363973563537
  saturation: 0.5432776003144681
  rhythmicContrast: 0.27606045827269554
purpose: []
